import discord
import datetime

from discord.ext import commands

from db.db import Database

class Profile(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot: commands.Bot = bot
        self.db: Database = Database()

    @commands.hybrid_command()
    async def profile(self, ctx: commands.Context):
        """
        View your Leetcode profile and various statistics
        """
        
        discord_user_id = ctx.message.author.id

        user = self.db.find_user(discord_user_id)

        if not user:
            await ctx.send(f"{ctx.message.author.mention}, your " + \
                            "profile currently does not exist in the " + \
                            "database. Create your profile by following " + \
                            "the instructions in /setupprofile")
            return
        
        embed = discord.Embed()

        embed.set_author(name=user["discord_username"], icon_url=ctx.message.author.display_avatar)
        embed.set_thumbnail(url=ctx.message.author.display_avatar)

        embed.title = f"{user['lc_user_name']}'s Leetcode Profile"
        embed.url = f"https://leetcode.com/u/{user['lc_user_name']}/"

        embed.add_field(name="Ratings", value="", inline=False)
        embed.add_field(name="Overall Rating", value="{:0.0f}".format(user["projected_rating"]), inline=True)
        embed.add_field(name="Contest Rating", value="{:0.0f}".format(user["contest_rating"]), inline=True)
        embed.add_field(name="Questions Rating", value="{:0.0f}".format(user["questions_rating"]), inline=True)
        embed.add_field(name=chr(173), value=chr(173))

        embed.add_field(name="Skillsets", value="", inline=False)
        for tag in user["tags"]:
            if tag["slug"] == "overall":
                continue
            
            embed.add_field(name=tag["slug"], value="{:0.0f}".format(tag["rating"]), inline=True)

        # TODO: put settings not in profile

        embed.timestamp = datetime.datetime.now()
        embed.set_footer(text="Generated by Leetcode Improvement Tool", icon_url="")

        await ctx.send(embed=embed)